<template>
    <!-- <div>
        <NuxtLayout name="header"> Hello world! </NuxtLayout> -->
    <div><Login /></div>

    <!-- </div> -->
</template>

<script setup>
import Login from './LoginPage/Login.vue'

onMounted(async () => {
    useHead({
        bodyAttrs: {
            class: ['bg-pan-left'],
        },
    })
})
</script>

<style>
html {
    background: linear-gradient(-45deg, #d13100, #000000, #009ad2, #147961) repeat !important;
    background-size: 400% 400% !important;
    background-position-x: -175px;
    background-position-y: 0px;
}

.bg-pan-left {
    -webkit-animation: bg-pan-left 8s both;
    animation: bg-pan-left 8s both;
}

/* ----------------------------------------------
 * Generated by Animista on 2022-6-25 17:31:23
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation bg-pan-left
 * ----------------------------------------
 */
@-webkit-keyframes bg-pan-left {
    0% {
        background-position: 100% 50%;
    }
    100% {
        background-position: 0% 50%;
    }
}
@keyframes bg-pan-left {
    0% {
        background-position: 100% 50%;
    }
    100% {
        background-position: 0% 50%;
    }
}
</style>
